server:
  port: 9090
  address: localhost
spring:
  application:
    name: core
  data:
    mongodb:
      database: blog
      host: localhost
      port: 27017
      repositories:
        enabled: true




