server:
  port: 8090
  address: localhost
spring:
  application:
    name: auth

security:
  oauth2:
    client:
      clientId: auth
      clientSecret: auth
      accessTokenUri: http://localhost:8090/oauth/token
      grant-type: password
      scope: server
    resource:
      filter-order: 3


